#prueba:
#    path:  /test
#    defaults: { _controller: BackendBundle:Home:test }
#    methods:  [GET]

# ------------------------------------------------------------------------------------------------
# * Article Routes *******************************************************************************
# ------------------------------------------------------------------------------------------------
public.article.preview:
    path:  /articulo/vista-previa/{id}
    defaults: { _controller: BackendBundle:Article:PreviewArticle }
    methods:  [POST]
    requirements:
        page: \d+

public.article.search:
    path:  /articulo/buscar
    defaults: { _controller: BackendBundle:Article:SearchArticle }
    methods:  [GET]

public.article.show:
    path:  /articulo/{slug}
    defaults: { _controller: BackendBundle:Article:ShowArticle }
    methods:  [GET]

# ------------------------------------------------------------------------------------------------
# * Category Routes ******************************************************************************
# ------------------------------------------------------------------------------------------------
public.category.list:
    path:  /articulos
    defaults: { _controller: BackendBundle:Category:ListCategories }
    methods:  [GET]

public.category.show:
    path:  /categoria/{slug}
    defaults: { _controller: BackendBundle:Category:ShowCategory }
    methods:  [GET]

# ------------------------------------------------------------------------------------------------
# * Comment Routes *******************************************************************************
# ------------------------------------------------------------------------------------------------
public.comment.add:
    path:  /articulo/{id}/comentario
    defaults: { _controller: BackendBundle:Comment:Add, scope: 'public' }
    methods:  [POST]
    requirements:
        page: \d+

# ------------------------------------------------------------------------------------------------
# * Homepage Routes ******************************************************************************
# ------------------------------------------------------------------------------------------------
public.home:
    path:  /
    defaults: { _controller: BackendBundle:Home:Index }
    methods:  [GET]

# ------------------------------------------------------------------------------------------------
# * Contact Routes *******************************************************************************
# ------------------------------------------------------------------------------------------------
public.contact:
    path:  /contacto
    defaults: { _controller: BackendBundle:Cms:Contact }
    methods:  [GET, POST]

# ------------------------------------------------------------------------------------------------
# * Institution Routes ***************************************************************************
# ------------------------------------------------------------------------------------------------
public.net.index:
    path: /red
    defaults: { _controller: BackendBundle:Net:Index }
    methods:  [GET]
    requirements:
        page: \d+

public.net.center.index:
    path: /red/centros
    defaults: { _controller: BackendBundle:Net:IndexCenter }
    methods:  [GET]
    requirements:
        page: \d+

public.net.center.show:
    path: /red/centros/{slug}
    defaults: { _controller: BackendBundle:Net:ShowCenter }
    methods:  [GET]
    requirements:
        page: \d+

public.net.promoter.index:
    path: /red/promotores
    defaults: { _controller: BackendBundle:Net:IndexPromoter }
    methods:  [GET]
    requirements:
        page: \d+

public.net.promoter.show:
    path: /red/promotores/{slug}
    defaults: { _controller: BackendBundle:Net:ShowPromoter }
    methods:  [GET]
    requirements:
        page: \d+

# ------------------------------------------------------------------------------------------------
# * User Routes **********************************************************************************
# ------------------------------------------------------------------------------------------------
public.user.login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }
    methods:  [GET]
    
public.user.show:
    path:  /usuario/{id}
    defaults: { _controller: BackendBundle:User:Show }
    methods:  [GET]
    requirements:
        page: \d+

public.user.registration.options:
    path: /registro
    defaults: { _controller: BackendBundle:User:RegistrationOptions }
    methods:  [GET]

public.user.registration.default:
    path: /registro/default
    defaults: { _controller: FOSUserBundle:Registration:register }
    methods:  [GET, POST]

public.user.registration.facebook:
    path: /registro/facebook
    defaults: { _controller: BackendBundle:User:RegistrationOptions }
    methods:  [GET, POST]

public.user.registration.twitter:
    path: /registro/twitter
    defaults: { _controller: BackendBundle:User:RegistrationOptions }
    methods:  [GET, POST]

public.user.registration.checkEmail:
    path: /comprueba-tu-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    methods:  [GET, POST]

public.user.registration.confirm:
    path: /confirmar/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    methods:  [GET, POST]

public.user.registration.confirmed:
    path: /confirmado
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    methods:  [GET, POST]

public.user.resetting.sendEmail:
    path: /recuperar-password/envia-email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }
    methods:  [GET, POST]

public.user.resetting.checkEmail:
    path: /recuperar-password/comprueba-email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail }
    methods:  [GET, POST]

public.user.resetting.password:
    path: /recuperar-password/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
    methods:  [GET, POST]

# ------------------------------------------------------------------------------------------------
# * Cms Routes ***********************************************************************************
# ------------------------------------------------------------------------------------------------
public.helpPage.show:
    path:  /ayuda/{slug}
    defaults: { _controller: BackendBundle:Cms:ShowHelpPage, slug: null }
    methods:  [GET]

public.cms.static:
    path:  /{slug}
    defaults: { _controller: BackendBundle:Cms:Static }
    methods:  [GET]