<?php

namespace Uzink\ConfiguracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArbolPaginasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametroConfiguracionRepository extends EntityRepository
{
}
