services:
    parametroconfiguracion_bundle.manager.parametroconfiguracion:
        class: Uzink\ConfiguracionBundle\Entity\ParametroConfiguracionManager
        arguments:
            - "@event_dispatcher"
            - "@doctrine.orm.entity_manager"
            - Uzink\ConfiguracionBundle\Entity\ParametroConfiguracion
        scope: request
