parameters:
    proun.user.handler.class: Proun\RestBundle\Handler\UserHandler
    proun.user.class: Proun\BackendBundle\Entity\User
    proun.request.handler.class: Proun\RestBundle\Handler\RequestHandler
    proun.request.class: Proun\BackendBundle\Entity\Request    
    
services:
    proun.user.handler:
        class: "%proun.user.handler.class%"
        arguments:
            om: "@doctrine.orm.entity_manager"
            entityClass: "%proun.user.class%"
            formFactory: "@form.factory"
            um: "@fos_user.user_manager"
    proun.request.handler:
        class: "%proun.request.handler.class%"
        arguments:
            om: "@doctrine.orm.entity_manager"
            entityClass: "%proun.request.class%"
            formFactory: "@form.factory"
            um: "@fos_user.user_manager"            
            
  