admin.article.index:
    path:  /list/{page}
    defaults: { _controller: AdminBundle:Article:index, page: 1 }
    methods:  [GET]
    requirements:
        page: \d+

admin.article.new:
    path:  /new
    defaults: { _controller: AdminBundle:Article:new }
    methods:  [GET]
    requirements:
        id: \d+

admin.article.create:
    path:  /create
    defaults: { _controller: AdminBundle:Article:create }
    methods:  [POST]

admin.article.edit:
    path:  /{id}/edit
    defaults: { _controller: AdminBundle:Article:edit }
    methods:  [GET]
    requirements:
        id: \d+

admin.article.update:
    path:  /{id}/update
    defaults: { _controller: AdminBundle:Article:update }
    methods:  [POST, PUT]
    requirements:
        id: \d+

admin.article.delete:
    path:  /{id}/delete
    defaults: { _controller: AdminBundle:Article:delete }
    methods:  [GET, POST]
    requirements:
        id: \d+

admin.article.confirm.delete:
    path:  /{id}/confirm-delete
    defaults: { _controller: AdminBundle:Article:confirmDelete }
    methods:  [POST]
    requirements:
        id: \d+
