admin.category.index:
    path:  /list/{page}
    defaults: { _controller: AdminBundle:Category:index, page: 1 }
    methods:  [GET]
    requirements:
        page: \d+

admin.category.new:
    path:  /new
    defaults: { _controller: AdminBundle:Category:new }
    methods:  [GET]
    requirements:
        id: \d+

admin.category.create:
    path:  /create
    defaults: { _controller: AdminBundle:Category:create }
    methods:  [POST]

admin.category.edit:
    path:  /{id}/edit
    defaults: { _controller: AdminBundle:Category:edit }
    methods:  [GET]
    requirements:
        id: \d+

admin.category.update:
    path:  /{id}/update
    defaults: { _controller: AdminBundle:Category:update }
    methods:  [POST, PUT]
    requirements:
        id: \d+

admin.category.delete:
    path:  /{id}/delete
    defaults: { _controller: AdminBundle:Category:delete }
    methods:  [GET, POST]
    requirements:
        id: \d+

admin.category.confirm.delete:
    path:  /{id}/confirm-delete
    defaults: { _controller: AdminBundle:Category:confirmDelete }
    methods:  [POST]
    requirements:
        id: \d+
