admin.contact.index:
    path:  /list/{page}
    defaults: { _controller: AdminBundle:Contact:index, page: 1 }
    methods:  [GET]
    requirements:
        page: \d+

admin.contact.new:
    path:  /new
    defaults: { _controller: AdminBundle:Contact:new }
    methods:  [GET]
    requirements:
        id: \d+

admin.contact.create:
    path:  /create
    defaults: { _controller: AdminBundle:Contact:create }
    methods:  [POST]

admin.contact.edit:
    path:  /{id}/edit
    defaults: { _controller: AdminBundle:Contact:edit }
    methods:  [GET]
    requirements:
        id: \d+

admin.contact.update:
    path:  /{id}/update
    defaults: { _controller: AdminBundle:Contact:update }
    methods:  [POST, PUT]
    requirements:
        id: \d+

admin.contact.delete:
    path:  /{id}/delete
    defaults: { _controller: AdminBundle:Contact:delete }
    methods:  [POST]
    requirements:
        id: \d+
