admin.helpPage.index:
    path:  /list/{role}/{page}
    defaults: { _controller: AdminBundle:HelpPage:list, page: 1 }
    methods:  [GET]
    requirements:
        role: "usuario|editor|supervisor|lider"
        page: \d+

admin.helpPage.new:
    path:  /new/{role}
    defaults: { _controller: AdminBundle:HelpPage:new }
    methods:  [GET]
    requirements:
        role: "usuario|editor|supervisor|lider"

admin.helpPage.create:
    path:  /create/{role}
    defaults: { _controller: AdminBundle:HelpPage:create }
    methods:  [POST]
    requirements:
        role: "usuario|editor|supervisor|lider"

admin.helpPage.edit:
    path:  /{id}/edit
    defaults: { _controller: AdminBundle:HelpPage:edit }
    methods:  [GET]
    requirements:
        id: \d+

admin.helpPage.update:
    path:  /{id}/update
    defaults: { _controller: AdminBundle:HelpPage:update }
    methods:  [POST, PUT]
    requirements:
        id: \d+

admin.helpPage.delete:
    path:  /{id}/delete
    defaults: { _controller: AdminBundle:HelpPage:delete }
    methods:  [POST]
    requirements:
        id: \d+
