admin.page.index:
    pattern:  /list/{page}
    defaults: { _controller: AdminBundle:Page:index, page: 1 }
    methods:  [GET]
    requirements:
        page: \d+

admin.page.new:
    pattern:  /new
    defaults: { _controller: AdminBundle:Page:new }
    methods:  [GET]
    requirements:
        id: \d+

admin.page.create:
    pattern:  /create
    defaults: { _controller: AdminBundle:Page:create }
    methods:  [POST]

admin.page.edit:
    pattern:  /{id}/edit
    defaults: { _controller: AdminBundle:Page:edit }
    methods:  [GET]
    requirements:
        id: \d+

admin.page.update:
    pattern:  /{id}/update
    defaults: { _controller: AdminBundle:Page:update }
    methods:  [POST, PUT]
    requirements:
        id: \d+

admin.page.delete:
    pattern:  /{id}/delete
    defaults: { _controller: AdminBundle:Page:delete }
    methods:  [POST]
    requirements:
        id: \d+
